##############################################
# Application Configuration
##############################################

# Server Config
server.port=8092
spring.application.name=Corporate-Accounts-Service

##############################################
# Logging Configuration
##############################################
# Log level (TRACE, DEBUG, INFO, WARN, ERROR)
logging.level.root=INFO
logging.level.com.iexceed.appzillon=DEBUG

# Log file (uncomment if file logging needed)
# logging.file.name=logs/corporate-accounts-service.log

##############################################
# External API Config
##############################################
# Postman Mock API Base URL
external.api.corporate-details.base-url=https://f1e02a7b-ebc2-4fa9-9aa8-ca5fc12935dc.mock.pstmn.io

# Endpoint path (keep it separate for reusability)
external.api.corporate-details.endpoint=/corporate-details
